// src/components/modals/XmlModal.vue
<script setup lang="ts">
import { xmlModal, closeXmlModal } from "@/composables/useModals";
import { copyText } from "@/composables/useToast";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogFooter,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";

function onOpenChange(open: boolean): void {
  if (!open) closeXmlModal();
}
</script>

<template>
  <Dialog :open="xmlModal.visible" @update:open="onOpenChange">
    <DialogContent class="sm:max-w-2xl">
      <DialogHeader>
        <DialogTitle>Entry XML</DialogTitle>
      </DialogHeader>
      <pre
        class="bg-muted text-muted-foreground max-h-[60vh] overflow-auto rounded-md border p-3 font-mono text-xs leading-relaxed whitespace-pre"
        >{{ xmlModal.content }}</pre
      >
      <DialogFooter>
        <Button variant="outline" @click="copyText(xmlModal.content, 'XML')">
          Copy
        </Button>
        <Button variant="outline" @click="closeXmlModal">Close</Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>

// src/components/modals/XmlModal.tsx
import { useModals, closeXmlModal } from "@/stores/modals";
import { copyText } from "@/stores/toast";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";

export default function XmlModal() {
  const visible = useModals((s) => s.xmlVisible);
  const content = useModals((s) => s.xmlContent);

  return (
    <Dialog open={visible} onOpenChange={(o) => !o && closeXmlModal()}>
      <DialogContent className="sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle>Entry XML</DialogTitle>
        </DialogHeader>
        <pre className="font-mono-code bg-muted text-muted-foreground max-h-[60vh] overflow-auto rounded-md border p-3 text-xs leading-relaxed whitespace-pre">
          {content}
        </pre>
        <DialogFooter>
          <Button variant="outline" onClick={() => copyText(content, "XML")}>
            Copy
          </Button>
          <Button variant="outline" onClick={closeXmlModal}>
            Close
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
