// src/components/screens/UnlockScreen.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";
import { invoke } from "@tauri-apps/api/core";
import { store, sourceLabel } from "../../store";
import { resumePendingAutotype } from "../../composables/useAutotype";
import type { VaultData } from "../../types";

const error = ref("");
const password = ref("");
const unlocking = ref(false);
const passInput = ref<HTMLInputElement | null>(null);

async function submit(): Promise<void> {
  error.value = "";
  if (!password.value) {
    error.value = "Password is required.";
    return;
  }
  unlocking.value = true;
  try {
    const vault = await invoke<VaultData>("open_database", {
      password: password.value,
    });
    store.vaultData = vault;
    store.masterPassword = password.value;
    store.selectedGroupUuid = vault.groups[0]?.uuid ?? null;
    store.selectedEntryUuid = null;
    store.searchQuery = "";
    store.editMode = false;
    store.screen = "vault";
    password.value = "";

    // If an auto-type hotkey arrived while locked, resume it now.
    await resumePendingAutotype();
  } catch (err) {
    error.value = String(err);
    passInput.value?.select();
  } finally {
    unlocking.value = false;
  }
}

function changeDb(): void {
  store.screen = "config";
}

onMounted(() => passInput.value?.focus());
</script>

<template>
  <div id="screen-unlock" class="screen active">
    <div class="auth-box">
      <div class="logo">
        <h1>KeeRust</h1>
        <p>Enter your master password</p>
      </div>
      <div class="vault-source">{{ sourceLabel() }}</div>
      <form novalidate @submit.prevent="submit">
        <div class="form-group">
          <label for="master-pass">Master Password</label>
          <input
            id="master-pass"
            ref="passInput"
            v-model="password"
            type="password"
            autocomplete="off"
          />
        </div>
        <div class="error" :class="{ visible: error }">{{ error }}</div>
        <button type="submit" class="btn" :disabled="unlocking">
          {{ unlocking ? "Unlocking…" : "Unlock" }}
        </button>
      </form>
      <button class="link-btn" @click="changeDb">Change database</button>
    </div>
  </div>
</template>

// src/components/screens/UnlockScreen.tsx
import { useEffect, useRef, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { setApp, sourceLabel } from "../../store";
import { resumePendingAutotype } from "../../stores/autotype";
import type { VaultData } from "../../types";

export default function UnlockScreen() {
  const [error, setError] = useState("");
  const [password, setPassword] = useState("");
  const [unlocking, setUnlocking] = useState(false);
  const passRef = useRef<HTMLInputElement | null>(null);

  useEffect(() => {
    passRef.current?.focus();
  }, []);

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    setError("");
    if (!password) {
      setError("Password is required.");
      return;
    }
    setUnlocking(true);
    try {
      const vault = await invoke<VaultData>("open_database", { password });
      setApp({
        vaultData: vault,
        masterPassword: password,
        selectedGroupUuid: vault.groups[0]?.uuid ?? null,
        selectedEntryUuid: null,
        searchQuery: "",
        editMode: false,
        screen: "vault",
      });
      setPassword("");
      // If an auto-type hotkey arrived while locked, resume it now.
      await resumePendingAutotype();
    } catch (err) {
      setError(String(err));
      passRef.current?.select();
    } finally {
      setUnlocking(false);
    }
  }

  return (
    <div id="screen-unlock" className="screen active">
      <div className="auth-box">
        <div className="logo">
          <h1>KeeRust</h1>
          <p>Enter your master password</p>
        </div>
        <div className="vault-source">{sourceLabel()}</div>
        <form noValidate onSubmit={submit}>
          <div className="form-group">
            <label htmlFor="master-pass">Master Password</label>
            <input
              id="master-pass"
              ref={passRef}
              type="password"
              autoComplete="off"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>
          <div className={"error" + (error ? " visible" : "")}>{error}</div>
          <button type="submit" className="btn" disabled={unlocking}>
            {unlocking ? "Unlocking…" : "Unlock"}
          </button>
        </form>
        <button className="link-btn" onClick={() => setApp({ screen: "config" })}>
          Change database
        </button>
      </div>
    </div>
  );
}
