// src/components/ThemeToggle.vue
<script setup lang="ts">
import { Moon, Sun } from "lucide-vue-next";
import { Button } from "@/components/ui/button";
import { useTheme } from "@/composables/useTheme";

const { theme, toggle } = useTheme();
</script>

<template>
  <Button
    variant="ghost"
    size="icon"
    :title="theme === 'dark' ? 'Switch to light theme' : 'Switch to dark theme'"
    aria-label="Toggle theme"
    @click="toggle"
  >
    <Sun v-if="theme === 'dark'" />
    <Moon v-else />
  </Button>
</template>

// src/components/ThemeToggle.tsx
import { Moon, Sun } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useTheme } from "@/components/theme-provider";

export default function ThemeToggle() {
  const { theme, toggle } = useTheme();
  return (
    <Button
      variant="ghost"
      size="icon"
      onClick={toggle}
      title={theme === "dark" ? "Switch to light theme" : "Switch to dark theme"}
      aria-label="Toggle theme"
    >
      {theme === "dark" ? <Sun /> : <Moon />}
    </Button>
  );
}
