// src/components/vault/DetailField.tsx
import { useState } from "react";
import { copyText } from "../../stores/toast";

export default function DetailField({
  label,
  value,
  isPassword,
  isUrl,
}: {
  label: string;
  value: string;
  isPassword?: boolean;
  isUrl?: boolean;
}) {
  const [revealed, setRevealed] = useState(false);
  if (!value) return null;

  const masked = isPassword && !revealed;

  return (
    <div className="detail-field">
      <div className="detail-label">{label}</div>
      <div className="detail-value">
        <span className={masked ? "masked" : ""}>
          {masked ? "••••••••••••" : value}
        </span>
        {isPassword && (
          <button className="icon-btn" onClick={() => setRevealed((r) => !r)}>
            {revealed ? "Hide" : "Show"}
          </button>
        )}
        <button className="icon-btn" onClick={() => copyText(value, label)}>
          Copy
        </button>
        {isUrl && (
          <button className="icon-btn" onClick={() => window.open(value, "_blank")}>
            Open
          </button>
        )}
      </div>
    </div>
  );
}

// src/components/vault/DetailField.vue
<script setup lang="ts">
import { ref } from "vue";
import { copyText } from "../../composables/useToast";

const props = defineProps<{
  label: string;
  value: string;
  isPassword?: boolean;
  isUrl?: boolean;
}>();

const revealed = ref(false);

function openUrl(): void {
  if (props.value) window.open(props.value, "_blank");
}
</script>

<template>
  <div v-if="value" class="detail-field">
    <div class="detail-label">{{ label }}</div>
    <div class="detail-value">
      <span :class="{ masked: isPassword && !revealed }">{{
        isPassword && !revealed ? "••••••••••••" : value
      }}</span>
      <button v-if="isPassword" class="icon-btn" @click="revealed = !revealed">
        {{ revealed ? "Hide" : "Show" }}
      </button>
      <button class="icon-btn" @click="copyText(value, label)">Copy</button>
      <button v-if="isUrl" class="icon-btn" @click="openUrl">Open</button>
    </div>
  </div>
</template>
