// src/components/vault/EntryEditForm.tsx
import { useEffect, useMemo, useRef, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { setApp, getApp, markSyncPending } from "../../store";
import { showToast } from "../../stores/toast";
import { avatarColor } from "../../lib/avatar";
import { iconEmoji } from "../../lib/icons";
import { DEFAULT_AT_SEQUENCE } from "../../lib/autotype";
import type { CustomField, EntryData, SaveResult } from "../../types";
import IconPicker from "./IconPicker";
import KeystrokeHelper from "./KeystrokeHelper";

export default function EntryEditForm({
  entry,
  onDone,
}: {
  entry: EntryData | null;
  onDone: () => void;
}) {
  const isNew = !entry;

  const base: EntryData = useMemo(
    () =>
      entry ?? {
        uuid: "",
        group_uuid:
          getApp().selectedGroupUuid || getApp().vaultData?.groups[0]?.uuid || "",
        title: "", username: "", password: "", url: "", notes: "",
        group_name: "",
        otp_uri: null, custom_fields: [], attachments: [], history: [],
        icon_id: 0, custom_icon_base64: null,
        autotype_enabled: true, autotype_sequence: "", autotype_obfuscation: false,
      },
    [entry]
  );

  const [title, setTitle] = useState(base.title);
  const [username, setUsername] = useState(base.username);
  const [password, setPassword] = useState(base.password);
  const [url, setUrl] = useState(base.url);
  const [notes, setNotes] = useState(base.notes);
  const [otpUri, setOtpUri] = useState(base.otp_uri || "");
  const [atEnabled, setAtEnabled] = useState(base.autotype_enabled !== false);
  const [atSeq, setAtSeq] = useState(base.autotype_sequence || "");
  const [atObf, setAtObf] = useState(base.autotype_obfuscation);
  const [customFields, setCustomFields] = useState<CustomField[]>(
    base.custom_fields.map((cf) => ({ ...cf }))
  );

  // Icon state: built-in index, or -1 to keep an existing custom icon.
  const [selectedIconId, setSelectedIconId] = useState<number>(
    typeof base.icon_id === "number" ? base.icon_id : 0
  );
  const [pendingCustomIcon, setPendingCustomIcon] = useState<string | null>(null);
  const existingCustomIcon = base.custom_icon_base64;

  const [showIconGrid, setShowIconGrid] = useState(false);
  const [showPassword, setShowPassword] = useState(false);
  const [showHelper, setShowHelper] = useState(false);
  const [saving, setSaving] = useState(false);

  const titleRef = useRef<HTMLInputElement | null>(null);
  const seqRef = useRef<HTMLInputElement | null>(null);

  useEffect(() => {
    titleRef.current?.focus();
  }, []);

  const previewCustomIcon =
    pendingCustomIcon || (selectedIconId < 0 ? existingCustomIcon : null);
  const avatarBg = previewCustomIcon ? "transparent" : avatarColor(title || "New");

  function pickBuiltin(id: number) {
    setSelectedIconId(id);
    setPendingCustomIcon(null);
    setShowIconGrid(false);
  }

  function onFavicon(b64: string) {
    setPendingCustomIcon(b64);
    setSelectedIconId(-1); // custom icon takes over
    setShowIconGrid(false);
  }

  function setCf(i: number, patch: Partial<CustomField>) {
    setCustomFields((prev) =>
      prev.map((cf, idx) => (idx === i ? { ...cf, ...patch } : cf))
    );
  }
  function addCustomField() {
    setCustomFields((prev) => [...prev, { name: "", value: "", protected: false }]);
  }
  function removeCustomField(i: number) {
    setCustomFields((prev) => prev.filter((_, idx) => idx !== i));
  }

  // Insert a keystroke token at the cursor in the sequence input.
  function insertToken(token: string) {
    const input = seqRef.current;
    const start = input?.selectionStart ?? atSeq.length;
    const end = input?.selectionEnd ?? atSeq.length;
    const next = atSeq.slice(0, start) + token + atSeq.slice(end);
    setAtSeq(next);
    requestAnimationFrame(() => {
      if (input) {
        const pos = start + token.length;
        input.focus();
        input.setSelectionRange(pos, pos);
      }
    });
  }

  async function save() {
    const t = title.trim();
    if (!t) {
      showToast("Title is required");
      return;
    }
    const cleanFields = customFields
      .filter((cf) => cf.name.trim())
      .map((cf) => ({ name: cf.name.trim(), value: cf.value, protected: cf.protected }));

    const update = {
      uuid: isNew ? "" : base.uuid,
      group_uuid: base.group_uuid,
      title: t,
      username,
      password,
      url,
      notes,
      otp_uri: otpUri.trim(),
      custom_fields: cleanFields,
      icon_id: selectedIconId, // -1 keeps an existing custom icon untouched
      custom_icon_base64: pendingCustomIcon, // set only when a favicon was downloaded
      autotype_enabled: atEnabled,
      autotype_sequence: atSeq.trim(),
      autotype_obfuscation: atObf,
    };

    setSaving(true);
    try {
      const result = await invoke<SaveResult>("save_entry", {
        password: getApp().masterPassword,
        entry: update,
      });
      setApp({
        vaultData: result.vault,
        selectedEntryUuid: result.saved_uuid,
        editMode: false,
      });
      showToast(isNew ? "Entry added" : "Entry saved");
      markSyncPending();
      onDone();
    } catch (err) {
      showToast("Save failed: " + String(err));
      setSaving(false);
    }
  }

  function cancel() {
    setApp({ editMode: false });
    onDone();
  }

  return (
    <div className="edit-form">
      <div className="edit-header">
        <button
          type="button"
          className="detail-avatar edit-avatar-btn"
          style={{ background: avatarBg }}
          title="Change icon"
          onClick={() => setShowIconGrid((v) => !v)}
        >
          {previewCustomIcon ? (
            <img
              className="avatar-img"
              src={`data:image/png;base64,${previewCustomIcon}`}
              alt=""
            />
          ) : (
            <span className="avatar-emoji">
              {iconEmoji(selectedIconId < 0 ? 0 : selectedIconId)}
            </span>
          )}
        </button>
        <input
          ref={titleRef}
          className="edit-title-input"
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          placeholder="Entry title"
          autoComplete="off"
        />
      </div>

      {showIconGrid && (
        <IconPicker
          selectedIconId={selectedIconId}
          url={url}
          onSelectBuiltin={pickBuiltin}
          onFavicon={onFavicon}
        />
      )}

      <div className="edit-section-header">Credentials</div>
      <div className="edit-field-group">
        <label className="edit-label">Username</label>
        <div className="edit-field-row">
          <input
            className="edit-input"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            placeholder="Username"
            autoComplete="off"
          />
        </div>
      </div>
      <div className="edit-field-group">
        <label className="edit-label">Password</label>
        <div className="edit-field-row">
          <input
            className="edit-input"
            type={showPassword ? "text" : "password"}
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            autoComplete="off"
          />
          <button
            className="icon-btn"
            type="button"
            onClick={() => setShowPassword((v) => !v)}
          >
            {showPassword ? "Hide" : "Show"}
          </button>
        </div>
      </div>
      <div className="edit-field-group">
        <label className="edit-label">URL</label>
        <div className="edit-field-row">
          <input
            className="edit-input"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            placeholder="https://"
            autoComplete="off"
          />
        </div>
      </div>

      <div className="edit-section-header">Notes</div>
      <textarea
        className="edit-textarea"
        value={notes}
        onChange={(e) => setNotes(e.target.value)}
        placeholder="Notes..."
      />

      <div className="edit-section-header">OTP</div>
      <div className="edit-field-row" style={{ marginBottom: "0.25rem" }}>
        <input
          className="edit-input"
          value={otpUri}
          onChange={(e) => setOtpUri(e.target.value)}
          placeholder="otpauth://totp/Account?secret=BASE32SECRET"
          autoComplete="off"
        />
      </div>

      <div className="edit-section-header">
        <span>Custom Fields</span>
        <button className="icon-btn" type="button" onClick={addCustomField}>
          + Add Field
        </button>
      </div>
      <div>
        {customFields.map((cf, i) => (
          <div key={i} className="edit-cf-row">
            <input
              className="edit-input edit-cf-name"
              value={cf.name}
              onChange={(e) => setCf(i, { name: e.target.value })}
              placeholder="Field name"
              autoComplete="off"
            />
            <input
              className="edit-input edit-cf-value"
              value={cf.value}
              onChange={(e) => setCf(i, { value: e.target.value })}
              placeholder="Value"
              autoComplete="off"
            />
            <label className="edit-cf-protected-label">
              <input
                type="checkbox"
                checked={cf.protected}
                onChange={(e) => setCf(i, { protected: e.target.checked })}
              />{" "}
              Protected
            </label>
            <button className="icon-btn" type="button" onClick={() => removeCustomField(i)}>
              ×
            </button>
          </div>
        ))}
      </div>

      <div className="edit-section-header">Auto-Type</div>
      <label className="edit-checkbox-row">
        <input
          type="checkbox"
          checked={atEnabled}
          onChange={(e) => setAtEnabled(e.target.checked)}
        />
        Enable auto-type for this entry
      </label>
      <div className="edit-field-group">
        <label className="edit-label">Keystrokes</label>
        <div className="edit-field-row at-seq-wrap">
          <input
            ref={seqRef}
            className="edit-input"
            value={atSeq}
            onChange={(e) => setAtSeq(e.target.value)}
            placeholder={DEFAULT_AT_SEQUENCE}
            autoComplete="off"
            onFocus={() => setShowHelper(true)}
            onBlur={() => setTimeout(() => setShowHelper(false), 150)}
          />
          {showHelper && <KeystrokeHelper onInsert={insertToken} />}
        </div>
        <div className="edit-at-hint">
          Click the field to insert fields, modifiers and keys. Empty = default sequence.
        </div>
      </div>
      <label className="edit-checkbox-row">
        <input
          type="checkbox"
          checked={atObf}
          onChange={(e) => setAtObf(e.target.checked)}
        />
        Mix real keystrokes with random
      </label>

      <div className="edit-actions">
        <button className="btn-save-entry" disabled={saving} onClick={save}>
          {saving ? "Saving…" : "Save"}
        </button>
        <button className="btn-cancel-entry" type="button" onClick={cancel}>
          Cancel
        </button>
      </div>
    </div>
  );
}

// src/components/vault/EntryEditForm.vue
<script setup lang="ts">
import { ref, reactive, computed, nextTick, onMounted } from "vue";
import { invoke } from "@tauri-apps/api/core";
import { store, markSyncPending } from "../../store";
import { showToast } from "../../composables/useToast";
import { avatarColor } from "../../lib/avatar";
import { iconEmoji } from "../../lib/icons";
import { DEFAULT_AT_SEQUENCE } from "../../lib/autotype";
import type { CustomField, EntryData, SaveResult } from "../../types";
import IconPicker from "./IconPicker.vue";
import KeystrokeHelper from "./KeystrokeHelper.vue";

const props = defineProps<{ entry: EntryData | null }>();
const emit = defineEmits<{ (e: "saved"): void; (e: "cancel"): void }>();

const isNew = computed(() => !props.entry);

const base: EntryData = props.entry ?? {
  uuid: "",
  group_uuid: store.selectedGroupUuid || store.vaultData?.groups[0]?.uuid || "",
  title: "", username: "", password: "", url: "", notes: "",
  group_name: "",
  otp_uri: null, custom_fields: [], attachments: [], history: [],
  icon_id: 0, custom_icon_base64: null,
  autotype_enabled: true, autotype_sequence: "", autotype_obfuscation: false,
};

// Editable form model (a copy, so cancel discards changes).
const form = reactive({
  title: base.title,
  username: base.username,
  password: base.password,
  url: base.url,
  notes: base.notes,
  otp_uri: base.otp_uri || "",
  autotype_enabled: base.autotype_enabled !== false,
  autotype_sequence: base.autotype_sequence || "",
  autotype_obfuscation: base.autotype_obfuscation,
});
const customFields = reactive<CustomField[]>(
  base.custom_fields.map((cf) => ({ ...cf }))
);

// Icon state: built-in index, or -1 to keep an existing custom icon.
const selectedIconId = ref<number>(typeof base.icon_id === "number" ? base.icon_id : 0);
const pendingCustomIcon = ref<string | null>(null); // freshly downloaded favicon
const existingCustomIcon = base.custom_icon_base64;

const showIconGrid = ref(false);
const showPassword = ref(false);
const showHelper = ref(false);
const saving = ref(false);

// Delay hiding so a token mousedown registers before blur tears the popup down.
function onSeqBlur(): void {
  setTimeout(() => (showHelper.value = false), 150);
}

const titleInput = ref<HTMLInputElement | null>(null);
const seqInput = ref<HTMLInputElement | null>(null);

const previewCustomIcon = computed<string | null>(
  () => pendingCustomIcon.value || (selectedIconId.value < 0 ? existingCustomIcon : null)
);
const avatarBg = computed(() =>
  previewCustomIcon.value ? "transparent" : avatarColor(form.title || "New")
);

function pickBuiltin(id: number): void {
  selectedIconId.value = id;
  pendingCustomIcon.value = null;
  showIconGrid.value = false;
}

function onFavicon(b64: string): void {
  pendingCustomIcon.value = b64;
  selectedIconId.value = -1; // custom icon takes over
  showIconGrid.value = false;
}

function addCustomField(): void {
  customFields.push({ name: "", value: "", protected: false });
}
function removeCustomField(i: number): void {
  customFields.splice(i, 1);
}

// Insert a keystroke token at the cursor in the sequence input.
function insertToken(token: string): void {
  const input = seqInput.value;
  if (!input) return;
  const start = input.selectionStart ?? input.value.length;
  const end = input.selectionEnd ?? input.value.length;
  form.autotype_sequence =
    form.autotype_sequence.slice(0, start) + token + form.autotype_sequence.slice(end);
  nextTick(() => {
    const pos = start + token.length;
    input.focus();
    input.setSelectionRange(pos, pos);
  });
}

async function save(): Promise<void> {
  const title = form.title.trim();
  if (!title) {
    showToast("Title is required");
    return;
  }
  const cleanFields = customFields
    .filter((cf) => cf.name.trim())
    .map((cf) => ({ name: cf.name.trim(), value: cf.value, protected: cf.protected }));

  const update = {
    uuid: isNew.value ? "" : base.uuid,
    group_uuid: base.group_uuid,
    title,
    username: form.username,
    password: form.password,
    url: form.url,
    notes: form.notes,
    otp_uri: form.otp_uri.trim(),
    custom_fields: cleanFields,
    icon_id: selectedIconId.value, // -1 keeps an existing custom icon untouched
    custom_icon_base64: pendingCustomIcon.value, // set only when a favicon was downloaded
    autotype_enabled: form.autotype_enabled,
    autotype_sequence: form.autotype_sequence.trim(),
    autotype_obfuscation: form.autotype_obfuscation,
  };

  saving.value = true;
  try {
    const result = await invoke<SaveResult>("save_entry", {
      password: store.masterPassword,
      entry: update,
    });
    store.vaultData = result.vault;
    store.selectedEntryUuid = result.saved_uuid;
    store.editMode = false;
    showToast(isNew.value ? "Entry added" : "Entry saved");
    markSyncPending();
    emit("saved");
  } catch (err) {
    showToast("Save failed: " + String(err));
    saving.value = false;
  }
}

function cancel(): void {
  store.editMode = false;
  emit("cancel");
}

onMounted(() => titleInput.value?.focus());
</script>

<template>
  <div class="edit-form">
    <div class="edit-header">
      <button
        type="button"
        class="detail-avatar edit-avatar-btn"
        :style="{ background: avatarBg }"
        title="Change icon"
        @click="showIconGrid = !showIconGrid"
      >
        <img
          v-if="previewCustomIcon"
          class="avatar-img"
          :src="`data:image/png;base64,${previewCustomIcon}`"
          alt=""
        />
        <span v-else class="avatar-emoji">{{
          iconEmoji(selectedIconId < 0 ? 0 : selectedIconId)
        }}</span>
      </button>
      <input
        ref="titleInput"
        v-model="form.title"
        class="edit-title-input"
        placeholder="Entry title"
        autocomplete="off"
      />
    </div>

    <IconPicker
      v-if="showIconGrid"
      :selected-icon-id="selectedIconId"
      :url="form.url"
      @select-builtin="pickBuiltin"
      @favicon="onFavicon"
    />

    <div class="edit-section-header">Credentials</div>
    <div class="edit-field-group">
      <label class="edit-label">Username</label>
      <div class="edit-field-row">
        <input v-model="form.username" class="edit-input" placeholder="Username" autocomplete="off" />
      </div>
    </div>
    <div class="edit-field-group">
      <label class="edit-label">Password</label>
      <div class="edit-field-row">
        <input
          v-model="form.password"
          class="edit-input"
          :type="showPassword ? 'text' : 'password'"
          autocomplete="off"
        />
        <button class="icon-btn" type="button" @click="showPassword = !showPassword">
          {{ showPassword ? "Hide" : "Show" }}
        </button>
      </div>
    </div>
    <div class="edit-field-group">
      <label class="edit-label">URL</label>
      <div class="edit-field-row">
        <input v-model="form.url" class="edit-input" placeholder="https://" autocomplete="off" />
      </div>
    </div>

    <div class="edit-section-header">Notes</div>
    <textarea v-model="form.notes" class="edit-textarea" placeholder="Notes..."></textarea>

    <div class="edit-section-header">OTP</div>
    <div class="edit-field-row" style="margin-bottom: 0.25rem">
      <input
        v-model="form.otp_uri"
        class="edit-input"
        placeholder="otpauth://totp/Account?secret=BASE32SECRET"
        autocomplete="off"
      />
    </div>

    <div class="edit-section-header">
      <span>Custom Fields</span>
      <button class="icon-btn" type="button" @click="addCustomField">+ Add Field</button>
    </div>
    <div>
      <div v-for="(cf, i) in customFields" :key="i" class="edit-cf-row">
        <input v-model="cf.name" class="edit-input edit-cf-name" placeholder="Field name" autocomplete="off" />
        <input v-model="cf.value" class="edit-input edit-cf-value" placeholder="Value" autocomplete="off" />
        <label class="edit-cf-protected-label">
          <input type="checkbox" v-model="cf.protected" /> Protected
        </label>
        <button class="icon-btn" type="button" @click="removeCustomField(i)">×</button>
      </div>
    </div>

    <div class="edit-section-header">Auto-Type</div>
    <label class="edit-checkbox-row">
      <input type="checkbox" v-model="form.autotype_enabled" />
      Enable auto-type for this entry
    </label>
    <div class="edit-field-group">
      <label class="edit-label">Keystrokes</label>
      <div class="edit-field-row at-seq-wrap">
        <input
          ref="seqInput"
          v-model="form.autotype_sequence"
          class="edit-input"
          :placeholder="DEFAULT_AT_SEQUENCE"
          autocomplete="off"
          @focus="showHelper = true"
          @blur="onSeqBlur"
        />
        <KeystrokeHelper v-if="showHelper" @insert="insertToken" />
      </div>
      <div class="edit-at-hint">
        Click the field to insert fields, modifiers and keys. Empty = default sequence.
      </div>
    </div>
    <label class="edit-checkbox-row">
      <input type="checkbox" v-model="form.autotype_obfuscation" />
      Mix real keystrokes with random
    </label>

    <div class="edit-actions">
      <button class="btn-save-entry" :disabled="saving" @click="save">
        {{ saving ? "Saving…" : "Save" }}
      </button>
      <button class="btn-cancel-entry" type="button" @click="cancel">Cancel</button>
    </div>
  </div>
</template>
