// src/components/vault/OtpWidget.tsx
import { useEffect, useRef, useState } from "react";
import { parseOtpUri, computeTOTP } from "../../lib/totp";
import { copyText } from "../../stores/toast";

export default function OtpWidget({ otpUri }: { otpUri: string }) {
  const [code, setCode] = useState("------");
  const [pct, setPct] = useState(100);
  const [remaining, setRemaining] = useState(0);
  const [barClass, setBarClass] = useState("");
  const codeRef = useRef("------");

  useEffect(() => {
    const params = parseOtpUri(otpUri);
    if (!params.secret) return;
    let cancelled = false;

    async function refresh() {
      const now = Math.floor(Date.now() / 1000);
      const elapsed = now % params.period;
      const rem = params.period - elapsed;
      setRemaining(rem);
      setPct((rem / params.period) * 100);
      setBarClass(rem <= 5 ? "danger" : rem <= 10 ? "warn" : "");

      if (elapsed === 0 || codeRef.current === "------") {
        const c = await computeTOTP(
          params.secret,
          params.period,
          params.digits,
          params.algorithm
        );
        if (!cancelled) {
          codeRef.current = c || "------";
          setCode(codeRef.current);
        }
      }
    }

    refresh();
    const id = setInterval(refresh, 1000);
    return () => {
      cancelled = true;
      clearInterval(id);
    };
  }, [otpUri]);

  async function copyCode() {
    if (code && code !== "------") await copyText(code, "OTP");
  }

  return (
    <div className="detail-field">
      <div className="detail-label">One-Time Password</div>
      <div className="otp-widget">
        <span className="otp-code">{code}</span>
        <div className="otp-progress">
          <div className={"otp-bar" + (barClass ? " " + barClass : "")} style={{ width: pct + "%" }} />
        </div>
        <span className="otp-secs">{remaining}s</span>
        <button className="icon-btn" onClick={copyCode}>
          Copy
        </button>
      </div>
    </div>
  );
}

// src/components/vault/OtpWidget.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";
import { parseOtpUri, computeTOTP } from "../../lib/totp";
import { copyText } from "../../composables/useToast";

const props = defineProps<{ otpUri: string }>();

const code = ref("------");
const pct = ref(100);
const remaining = ref(0);
const barClass = ref("");

let timer: ReturnType<typeof setInterval> | undefined;
const params = parseOtpUri(props.otpUri);

async function refresh(): Promise<void> {
  const now = Math.floor(Date.now() / 1000);
  const elapsed = now % params.period;
  const rem = params.period - elapsed;
  remaining.value = rem;
  pct.value = (rem / params.period) * 100;
  barClass.value = rem <= 5 ? "danger" : rem <= 10 ? "warn" : "";

  // Only recompute the code on a new period boundary (or first run).
  if (elapsed === 0 || code.value === "------") {
    const c = await computeTOTP(
      params.secret,
      params.period,
      params.digits,
      params.algorithm
    );
    code.value = c || "------";
  }
}

async function copyCode(): Promise<void> {
  if (code.value && code.value !== "------") await copyText(code.value, "OTP");
}

onMounted(() => {
  if (!params.secret) return;
  refresh();
  timer = setInterval(refresh, 1000);
});

onUnmounted(() => {
  if (timer) clearInterval(timer);
});
</script>

<template>
  <div class="detail-field">
    <div class="detail-label">One-Time Password</div>
    <div class="otp-widget">
      <span class="otp-code">{{ code }}</span>
      <div class="otp-progress">
        <div class="otp-bar" :class="barClass" :style="{ width: pct + '%' }"></div>
      </div>
      <span class="otp-secs">{{ remaining }}s</span>
      <button class="icon-btn" @click="copyCode">Copy</button>
    </div>
  </div>
</template>
