// src/components/ui/sonner/Sonner.vue
<script setup lang="ts">
import { Toaster, type ToasterProps } from "vue-sonner";
import { useTheme } from "@/composables/useTheme";

const props = defineProps<ToasterProps>();
const { theme } = useTheme();
</script>

<template>
  <Toaster
    v-bind="props"
    :theme="theme"
    class="toaster group"
    :style="{
      '--normal-bg': 'var(--popover)',
      '--normal-text': 'var(--popover-foreground)',
      '--normal-border': 'var(--border)',
    }"
  />
</template>

// src/components/ui/sonner.tsx
import type { CSSProperties } from "react";
import { Toaster as Sonner, type ToasterProps } from "sonner";
import { useTheme } from "@/components/theme-provider";

function Toaster({ ...props }: ToasterProps) {
  const { theme } = useTheme();
  return (
    <Sonner
      theme={theme}
      className="toaster group"
      style={
        {
          "--normal-bg": "var(--popover)",
          "--normal-text": "var(--popover-foreground)",
          "--normal-border": "var(--border)",
        } as CSSProperties
      }
      {...props}
    />
  );
}

export { Toaster };
